### ISSUE TITLE
please add LICENSE file and attribute in package.json

### ISSUE THREAD

**Issue by GitMensch** [vinshuka/Cobol-Pretty-Headers#1]
Thanks for providing this extension, I'd like to use that but actually I don't know what license this is under. Possibly Public Domain or MIT-Licensed, but I don't know.

For the vsix, the likely most important thing is to add the missing the license attribute to package.json, please do that according to [package.json specs][2] with a valid [SPDX identifier][3].

Ideally add the license file via GitHub as described in the docs [adding a license to a repository][1], this will show the correct license also on GitHub and other code repositories..

Last missing piece: I highly suggest to also add a copyright and license note to the source files.

[1]:https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository
[2]:https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license
[3]:https://spdx.org/licenses/

**Comment by vinshuka** [comment]
Thank you for the detailed comment, I have added the license and updated the package.json and source files with license and copyright information.
