### ISSUE TITLE
move vsix from repo to releases

### ISSUE THREAD

**Issue by GitMensch** [vinshuka/Cobol-Pretty-Headers#3]
We already have a release at https://github.com/vinshuka/Cobol-Pretty-Headers/releases, I suggest to "edit" that, attaching the vsix there - and then delete it from the repo.
For new releases this can both be done manually or via some GH action or via github-cli.

**Comment by vinshuka** [comment]
done.

**Comment by GitMensch** [comment]
Somehow the 1.00 release got lost on the way, but that's possibly no too big deal...
